- This folder contains the notebook codes used for training participants in the HAI competition.
- These code were built with code provided by pytorch and torchvision, and implemented by Nam, J., .Jeong, J. and Shin, Y.
- Data is from the HAI competition organizers.
